// <auto-generated />
using System;
using AutomationRadar.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace AutomationRadar.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AutomationRadar.Model.Entities.AutomationRisk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("HorizonYears")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Justification")
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("OccupationId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("RiskLevel")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Source")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("Id");

                    b.HasIndex("OccupationId");

                    b.ToTable("AUTOMATION_RISKS", (string)null);
                });

            modelBuilder.Entity("AutomationRadar.Model.Entities.CareerTransition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("FromOccupationId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasDefaultValue(1);

                    b.Property<string>("RecommendedActions")
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("ToOccupationId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("Id");

                    b.HasIndex("FromOccupationId");

                    b.HasIndex("ToOccupationId");

                    b.ToTable("CAREER_TRANSITIONS", (string)null);
                });

            modelBuilder.Entity("AutomationRadar.Model.Entities.Occupation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("Sector")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("Id");

                    b.ToTable("OCCUPATIONS", (string)null);
                });

            modelBuilder.Entity("AutomationRadar.Model.Entities.AutomationRisk", b =>
                {
                    b.HasOne("AutomationRadar.Model.Entities.Occupation", "Occupation")
                        .WithMany("AutomationRisks")
                        .HasForeignKey("OccupationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AUTOMATIONRISK_OCCUPATION");

                    b.Navigation("Occupation");
                });

            modelBuilder.Entity("AutomationRadar.Model.Entities.CareerTransition", b =>
                {
                    b.HasOne("AutomationRadar.Model.Entities.Occupation", "FromOccupation")
                        .WithMany("SourceTransitions")
                        .HasForeignKey("FromOccupationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TRANSITION_FROM");

                    b.HasOne("AutomationRadar.Model.Entities.Occupation", "ToOccupation")
                        .WithMany("TargetTransitions")
                        .HasForeignKey("ToOccupationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TRANSITION_TO");

                    b.Navigation("FromOccupation");

                    b.Navigation("ToOccupation");
                });

            modelBuilder.Entity("AutomationRadar.Model.Entities.Occupation", b =>
                {
                    b.Navigation("AutomationRisks");

                    b.Navigation("SourceTransitions");

                    b.Navigation("TargetTransitions");
                });
#pragma warning restore 612, 618
        }
    }
}
